# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: user.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nuser.proto\x1a\x1bgoogle/protobuf/empty.proto\"@\n\x11PassWordCheckInfo\x12\x10\n\x08password\x18\x01 \x01(\t\x12\x19\n\x11\x65ncryptedPassword\x18\x02 \x01(\t\"(\n\x15\x43heckPassWordResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"%\n\x08PageInfo\x12\n\n\x02pn\x18\x01 \x01(\r\x12\r\n\x05pSize\x18\x02 \x01(\r\"\x1f\n\rMobileRequest\x12\x0e\n\x06mobile\x18\x01 \x01(\t\"\x17\n\tIdRequset\x12\n\n\x02id\x18\x01 \x01(\x05\"D\n\x0e\x43reateUserInfo\x12\x10\n\x08nickName\x18\x01 \x01(\t\x12\x10\n\x08passWord\x18\x02 \x01(\t\x12\x0e\n\x06mobile\x18\x03 \x01(\t\"P\n\x0eUpdateUserInfo\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x10\n\x08nickName\x18\x02 \x01(\t\x12\x0e\n\x06gender\x18\x03 \x01(\t\x12\x10\n\x08\x62irthDay\x18\x04 \x01(\x04\"\x82\x01\n\x10UserInfoResponse\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x10\n\x08passWord\x18\x02 \x01(\t\x12\x0e\n\x06mobile\x18\x03 \x01(\t\x12\x10\n\x08nickName\x18\x04 \x01(\t\x12\x10\n\x08\x62irthDay\x18\x05 \x01(\x04\x12\x0e\n\x06gender\x18\x06 \x01(\t\x12\x0c\n\x04role\x18\x07 \x01(\x05\"A\n\x0fUserListResonse\x12\r\n\x05total\x18\x01 \x01(\x05\x12\x1f\n\x04\x64\x61ta\x18\x02 \x03(\x0b\x32\x11.UserInfoResponse2\xbc\x02\n\x04User\x12*\n\x0bGetUserList\x12\t.PageInfo\x1a\x10.UserListResonse\x12\x34\n\x0fGetUserByMobile\x12\x0e.MobileRequest\x1a\x11.UserInfoResponse\x12,\n\x0bGetUserById\x12\n.IdRequset\x1a\x11.UserInfoResponse\x12\x30\n\nCreateUser\x12\x0f.CreateUserInfo\x1a\x11.UserInfoResponse\x12\x35\n\nUpdateUser\x12\x0f.UpdateUserInfo\x1a\x16.google.protobuf.Empty\x12;\n\rCheckPassWord\x12\x12.PassWordCheckInfo\x1a\x16.CheckPassWordResponseB\tZ\x07.;protob\x06proto3')



_PASSWORDCHECKINFO = DESCRIPTOR.message_types_by_name['PassWordCheckInfo']
_CHECKPASSWORDRESPONSE = DESCRIPTOR.message_types_by_name['CheckPassWordResponse']
_PAGEINFO = DESCRIPTOR.message_types_by_name['PageInfo']
_MOBILEREQUEST = DESCRIPTOR.message_types_by_name['MobileRequest']
_IDREQUSET = DESCRIPTOR.message_types_by_name['IdRequset']
_CREATEUSERINFO = DESCRIPTOR.message_types_by_name['CreateUserInfo']
_UPDATEUSERINFO = DESCRIPTOR.message_types_by_name['UpdateUserInfo']
_USERINFORESPONSE = DESCRIPTOR.message_types_by_name['UserInfoResponse']
_USERLISTRESONSE = DESCRIPTOR.message_types_by_name['UserListResonse']
PassWordCheckInfo = _reflection.GeneratedProtocolMessageType('PassWordCheckInfo', (_message.Message,), {
  'DESCRIPTOR' : _PASSWORDCHECKINFO,
  '__module__' : 'user_pb2'
  # @@protoc_insertion_point(class_scope:PassWordCheckInfo)
  })
_sym_db.RegisterMessage(PassWordCheckInfo)

CheckPassWordResponse = _reflection.GeneratedProtocolMessageType('CheckPassWordResponse', (_message.Message,), {
  'DESCRIPTOR' : _CHECKPASSWORDRESPONSE,
  '__module__' : 'user_pb2'
  # @@protoc_insertion_point(class_scope:CheckPassWordResponse)
  })
_sym_db.RegisterMessage(CheckPassWordResponse)

PageInfo = _reflection.GeneratedProtocolMessageType('PageInfo', (_message.Message,), {
  'DESCRIPTOR' : _PAGEINFO,
  '__module__' : 'user_pb2'
  # @@protoc_insertion_point(class_scope:PageInfo)
  })
_sym_db.RegisterMessage(PageInfo)

MobileRequest = _reflection.GeneratedProtocolMessageType('MobileRequest', (_message.Message,), {
  'DESCRIPTOR' : _MOBILEREQUEST,
  '__module__' : 'user_pb2'
  # @@protoc_insertion_point(class_scope:MobileRequest)
  })
_sym_db.RegisterMessage(MobileRequest)

IdRequset = _reflection.GeneratedProtocolMessageType('IdRequset', (_message.Message,), {
  'DESCRIPTOR' : _IDREQUSET,
  '__module__' : 'user_pb2'
  # @@protoc_insertion_point(class_scope:IdRequset)
  })
_sym_db.RegisterMessage(IdRequset)

CreateUserInfo = _reflection.GeneratedProtocolMessageType('CreateUserInfo', (_message.Message,), {
  'DESCRIPTOR' : _CREATEUSERINFO,
  '__module__' : 'user_pb2'
  # @@protoc_insertion_point(class_scope:CreateUserInfo)
  })
_sym_db.RegisterMessage(CreateUserInfo)

UpdateUserInfo = _reflection.GeneratedProtocolMessageType('UpdateUserInfo', (_message.Message,), {
  'DESCRIPTOR' : _UPDATEUSERINFO,
  '__module__' : 'user_pb2'
  # @@protoc_insertion_point(class_scope:UpdateUserInfo)
  })
_sym_db.RegisterMessage(UpdateUserInfo)

UserInfoResponse = _reflection.GeneratedProtocolMessageType('UserInfoResponse', (_message.Message,), {
  'DESCRIPTOR' : _USERINFORESPONSE,
  '__module__' : 'user_pb2'
  # @@protoc_insertion_point(class_scope:UserInfoResponse)
  })
_sym_db.RegisterMessage(UserInfoResponse)

UserListResonse = _reflection.GeneratedProtocolMessageType('UserListResonse', (_message.Message,), {
  'DESCRIPTOR' : _USERLISTRESONSE,
  '__module__' : 'user_pb2'
  # @@protoc_insertion_point(class_scope:UserListResonse)
  })
_sym_db.RegisterMessage(UserListResonse)

_USER = DESCRIPTOR.services_by_name['User']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\007.;proto'
  _PASSWORDCHECKINFO._serialized_start=43
  _PASSWORDCHECKINFO._serialized_end=107
  _CHECKPASSWORDRESPONSE._serialized_start=109
  _CHECKPASSWORDRESPONSE._serialized_end=149
  _PAGEINFO._serialized_start=151
  _PAGEINFO._serialized_end=188
  _MOBILEREQUEST._serialized_start=190
  _MOBILEREQUEST._serialized_end=221
  _IDREQUSET._serialized_start=223
  _IDREQUSET._serialized_end=246
  _CREATEUSERINFO._serialized_start=248
  _CREATEUSERINFO._serialized_end=316
  _UPDATEUSERINFO._serialized_start=318
  _UPDATEUSERINFO._serialized_end=398
  _USERINFORESPONSE._serialized_start=401
  _USERINFORESPONSE._serialized_end=531
  _USERLISTRESONSE._serialized_start=533
  _USERLISTRESONSE._serialized_end=598
  _USER._serialized_start=601
  _USER._serialized_end=917
# @@protoc_insertion_point(module_scope)
